# Research Questions to Investigate

In this tutorial we will be assessing how to answer the following three questions:

1.  Does the amount of training a dog has completed (as reported by their owner on a survey) predict whether a dog will perform below or above chance (i.e., 50%) on the ostensive behavioral task?
2.  Does the amount of training a dog has completed predict whether a dog will perform below or above chance on the nonostensive behavioral task? 
3.  How much of the variability in whether a dog performs better on non-ostensive tasks compared to ostensive tasks can be explained by its behavioral traits (training, sex, age, etc.)?

The first two questions have a very similar structure to each other, with a slight change in our outcome (i.e., our dependent variable). These are the simpler forms of classification models, which compare one continuous variable to one discrete binary variable. Question three adds a number of predictor variables, yet the binary discrete dependent variable is changed to add information about both types of behavioral tasks instead of looking at one at a time. Hopefully by working through these three questions you will get a better sense of how to choose what models to run, how to choose between models to get the best performing model, and how to change code in each model to account for different parameters.
