{
  "hash": "fe11cc1c344e1a9e8944502f68d1118e",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n\n\n\n\n\n## Running your models\n\nNow after all that explanation we finally get to the good part, running the actual models!\n\nIn 2016 a package came out called `mlr` (machine learning in R) that created a suite of tools to create machine learning models quickly and efficiently in R. This package is the only R package we will need for this section of the tutorial. The `mlr` package breaks creating machine learning models into three smaller steps:\n\n1.  Define the [task]{#task}: This step consists of passing the data into an object and labeling what the outcome variable is.\n2.  Define the [learner]{#learner}/model: A learner defines the structure of the algorithm. In this step you define/list the model type you want to use (i.e., logistic regression, KNN, random forest, etc.) and then the specific [hyperparameters](glossary.qmd#hyperparameters) you want the model to use. (i.e., what k to use in a KNN model) Learner is not a general term used throughout machine learning but instead is specific to the `mlr` package. You can also think of this step as defining your model.\n3.  [Train]{#train} the model with the appropriate cross validation approach: Put it all together along with the specified cross validation approach. At this step you create an object that takes the task, learner, and any other additional features and uses that information to output the trained model you can use to make predictions.\n\n### Creating the Task\n\nTo define the [task](#task) we will use the `makeClassifTask()` which defines a classification task. If doing regression tasks, you would use the function `makeRegrTask()`. You then pass the data to the `data` argument, and the name of the predictor variables to the `target` argument. For our purposes, we will be defining three tasks because we have three research questions, each with slightly different data representing the different outcomes and predictors. Because we only want to pass the data that is absolutely necessary for each task, we have to make those data frames before we can use them in to create the Task.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Research Question #1\n#extract only the two columns from the large pre-processed training dataset we made in step 1 that are needed for the research question: training score and the ostensive binary outcome variable\ndata_RQ_1 <- training_data |>  \n  select(training_score, ostensive_binary) |>  \n    mutate(ostensive_binary = as.factor(ostensive_binary)) \n\n#Define the Task for RQ #1\ntask_RQ_1 <- makeClassifTask(data = data_RQ_1, target = \"ostensive_binary\")\n\n#Research Question #2\n#extract only the two columns from the large pre-processed dataset that are needed for the research question: training score and the nonostensive binary outcome variable\ndata_RQ_2 <- training_data |> \n  select(training_score, nonostensive_binary) |> \n  mutate(nonostensive_binary = as.factor(nonostensive_binary)) \n\n#Define the task for RQ #2\ntask_RQ_2 <- makeClassifTask(data = data_RQ_2, target = \"nonostensive_binary\")\n\n#Research Question #3\n#select the predictor variables we will be using and the outcome variable of os_best\ndata_RQ_3_factor <- training_data |> \n  select(sex:miscellaneous_score,nonos_best) |> \nmutate(across(c(sex, desexed, purebred, gaze_follow, nonos_best), as.factor))\n\ndata_RQ_3_numeric <- data_RQ_3_factor |> \nmutate(across(c(sex, desexed, purebred, gaze_follow), as.numeric))\n\n#Define the task for RQ #3\ntask_RQ_3_factor <- makeClassifTask(data = data_RQ_3_factor, target = \"nonos_best\")\n\ntask_RQ_3_numeric <- makeClassifTask(data = data_RQ_3_numeric, target = \"nonos_best\")\n```\n:::\n\n\n\n\n\n\nNow we have created all the tasks we will need for every model we run! That is why it is nice to define the data before you create the model. We save ourselves extra coding and make our coding more readable.\n\n### Creating Models for Question 1\n\nSince the [learner](#learner) defines the model we are using, we will need a learner for each model we plan to run. As we discussed in the previous section, we will be running 3 models for our first and second research questions and two models for our third.\n\nTo create a learner we need to use the `makeLearner()` function. We will pass to that function what type of algorithm we are using and if it is classification, regression, or unsupervised. We will only be using classification for this tutorial since we want to classify things into groups, so all of our algorithms will start with `classif`.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Creating the KNN learner for RQ1\n\nknn_learner_RQ_1 <- makeLearner(\"classif.knn\")\n```\n:::\n\n\n\n\n\n\nNow, we have our learner- but it's actually missing something: the hyperparameter of what k should be. We need to tell the model how many adjacent data points we want it to use to classify the validation set. Now, we could guess and just make it 3 because that is what we have seen in some examples, but let's let the math do it for us instead. We can use code to check a bunch of different values and then we can use the value that gives us the best prediction rates. Let's go!\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#finding the best value of k\n\n#define values to check. Best to check 1 through 10 to start.\nknnParamSpace_RQ_1 <- makeParamSet(makeDiscreteParam(\"k\", values = 1:10))\n#tell the computer to search every value of k we offered (1 thru 10)\ngridSearch_RQ_1 <- makeTuneControlGrid()\n#cross validate for the k finding\ncvForTuning <- makeResampleDesc(\"RepCV\", folds = 10, reps =20)\n#Use the tuneParams function and the task we made above to get the best k value\ntunedk_RQ_1 <- suppressMessages({ \n  tuneParams(\"classif.knn\", task = task_RQ_1, resampling = cvForTuning,\n                          par.set = knnParamSpace_RQ_1, control = gridSearch_RQ_1, show.info = F)\n  }) \n```\n:::\n\n\n\n\n\n\nYou will notice that in the `tunedk_RQ_1` I have the `suppressMessages()` function. This is not necessary when running models yourself, and can be deleted from the code. I have added this function throughout the tutorial so that many redundant messages aren't printed in the final document. You might want to keep this function in your code if you want only the absolutely necessary outputs.\n\nNow let's print the result of our tuning:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntunedk_RQ_1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTune result:\nOp. pars: k=9\nmmce.test.mean=0.2925956\n```\n\n\n:::\n:::\n\n\n\n\n\n\nA k of 9 gave us the best mmce or mean misclassification error. The mean misclassification error is a great way to check the prediction accuracy, as it is simply the proportion of cases classified as the wrong class. So currently we have 29% of our data being classed incorrectly. Let's add this k of 9 into our learner and keep going!\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Creating the KNN learner for RQ1\nknn_learner_RQ_1 <- makeLearner(\"classif.knn\", par.vals = list(\"k\"=9))\n```\n:::\n\n\n\n\n\n\nNow we need to put it all together to train our model and then perform cross validation. Remember we already made our cross validation argument in the cross validation section: `loocv <- makeResampleDesc(method = \"LOO\")`. The `resample()` function runs the model multiple times with the data from each of the different cross validation sets. We just have to feed it the task, learner, and cross validation arguments we made earlier.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Training the model while cross validating\nKNN_model_RQ_1 <- suppressMessages({ train(learner = knn_learner_RQ_1, task = task_RQ_1)\n  })\n\nloocv <- makeResampleDesc(method = \"LOO\") #cross validation procedure\n\n#Get a sense of how well the model will work in practice with cross validation\nKNN_model_RQ_1_loocv <- suppressMessages({ \n  resample(learner = knn_learner_RQ_1, task = task_RQ_1, \n           resampling = loocv, measures = list(mmce, acc))  \n  }) \n```\n:::\n\n\n\n\n\n\n\n\nNow that we made the model and then cross validated it using Leave one out cross validation, we can look at the loss/cost function to see how our model is performing. In this case our loss/cost functions are accuracy (acc) and mean misclassification error (mmce). The `aggr()` function gives you the two performance metrics I asked the model to pull out in the `measures` argument. A performance metric tells you how well the model predicted the correct category. As noted above, the **mmce** is mean misclassifications error or the proportion of incorrectly classified cases, and **acc** is the accuracy or the proportion of correctly classified cases. You will notice that the two together add up to 100%, so you really only need one or the other.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Performance\nKNN_model_RQ_1_loocv$aggr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmmce.test.mean  acc.test.mean \n     0.2984014      0.7015986 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nThis model didn't perform well. We are currently classifying 70% of the data correctly. Let's run some other models and see if we can do better than this.\n\nNext on our list is making a decision tree. The argument you will need to make a decision tree (NOT a random forest but just 1 tree) is `classif.rpart`.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Creating the learner for a Single decision tree\ndecisiontree_learner_RQ_1_and_2 <- makeLearner(\"classif.rpart\")\n```\n:::\n\n\n\n\n\n\nNow we can pass our learner to the `resample` function along with our cross-validation procedure and task.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Training the model \ndecision_tree_model_RQ_1 <- suppressMessages({ \n  train(learner = decisiontree_learner_RQ_1_and_2, \n        task = task_RQ_1)\n  })\n\n#Checking how well the model does using cross validating\ndecision_tree_model_RQ_1_loocv <- suppressMessages({ \n  resample(learner = decisiontree_learner_RQ_1_and_2, \n           task = task_RQ_1, resampling = loocv, \n           measures = list(mmce, acc))\n  })\n```\n:::\n\n\n\n\n\n\n\n\nNow let's check how well the decision tree model is working with the data by looking at our loss/cost function.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Performance of the Decision Tree\ndecision_tree_model_RQ_1_loocv$aggr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmmce.test.mean  acc.test.mean \n     0.2841918      0.7158082 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe decision tree did a little better than the KNN model did (70% vs 71.6%) but they currently look pretty similar. We won't see the final differences until they have been evaluated on new unseen data in Step 5. Something to look forward to!\n\nThe third and last model we want to test with this first research question is a SVM model. The SVM model is the most complex and computational expensive model and/that has multiple hyperparameters that need tuning. The four hyper parameters that are most important to tune are `kernel`, `cost`, `degree`, and `gamma`. Each of the four hyperparameters deals with changing the decision boundary slightly. A [Decision boundary](#db) is the hyper-plane (often line or squiggle) that separates the data into two classes.\n\n-   `kernel` - The kernel defines what type of line you want the algorithm to fit to the data. There are four possible options: a line, a polynomial, a radial (circle), or a sigmoid. You only need to check the last three because a one degree polynomial is the same as a line, and if you ask the computer to calculate both you are just wasting time and computational power.\n-   `cost` - This controls how tolerant you will be of misclassifications - i.e., how hard or soft the margin of the decision boundary is. If it's soft (larger number) it allows misclassifications. If it's hard (larger number) it doesn't allow any misclassifications.\n-   `degree` - This controls how \"bendy\" the decision boundary is. Higher values mean more bendy. The bendier/squigglier the line, the more it fits the testing data and usually the less it generalizes to new unseen data. See the [regularization section](#regularization) on overfitting/underfitting.\n-   `gamma` - This controls how much influence the algorithm gives to individual data points. Large values of Gamma mean more intricate decision boundaries (i.e., A more squiggly line that maps every point instead of generalizes with a more linear line) and more likely to have overfitting.\n\nNow we will define the hyperparameters that we want to tune with the same functions we used to define k up above.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Create vector listing the possible kernels you can \nkernels <- c(\"polynomial\", \"radial\", \"sigmoid\")\n\nsvm_parametercheck <- makeParamSet(makeDiscreteParam(\"kernel\", values = kernels),\n                                       makeIntegerParam(\"degree\", lower =1, upper = 3),\n                                       makeNumericParam(\"cost\", lower = 0.1, upper =10),\n                                       makeNumericParam(\"gamma\", lower = 0.1, upper = 10))\n```\n:::\n\n\n\n\n\n\nNow that we have defined what we want the computer to check we have to tell it how to search through the values. Previously, in the KNN model above, we just had the computer search every value between 1 and 10 with `makeTuneControlGrid()` but if we had the computer look through every value we specified above, we would be waiting a *very* long time. Instead we will ask the computer to randomly search through a smaller subsection of the values with the `makeTuneControlRandom` argument. You should search through as many as you have computer power for. Where to start depends on how many values you are searching through. Degree can only be 3 values, so if I was only tuning that hyperparameter, 3 would be the same as searching through every value. However, cost and gamma could be any value between 0.1 and 10, which has hundreds of possible values if we are only going to the hundredths place. Start with a number that would reasonably check at least 5% of values and then run it multiple times. If you consistently get the same values each time you run, you probably have a high enough maximum iteration (below this is defined under `maxit`) value. If you keep getting very different values each time you run it, increase the maximum iteration value iteratively until you have consistently in results.\n\nSince this is just an example, though we will choose a small number so it runs quickly. Let's do that now!\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrandomsearch <- makeTuneControlRandom(maxit = 50)\n```\n:::\n\n\n\n\n\n\nNext, we will tell our computer to run code using multiple cores (i.e., CPUS) of our computer at once. This helps speed up the computation process by using more of the computer. While the myth that humans only use 10% of their brains is false, computers really don't use all of their brain unless you tell them to. Check how many cores your computer has with `parallel::detectCores()`. My machine has 24 CPUS (as you can see in the output below), so we'll use all of them with the `parallelStartSocket` function. Note that if you use all of your cores, your computer can't really do anything else while it is working. So if you want to check email, browse the web, or keep coding during the computation, leave a core or two out.\n\nWe also need a cross validation set for this search. We could use the `cvForTuning` we made earlier with 10 folds and 20 repetitions of each, but that would create 200 iterations. With that many iterations `cvForTuning` is likely to find the best hyperparameters for our question - but it would take more than 30 minutes to complete on my 24 core machine. Instead, we will make a new cross validation approach called `cvForTuning2` with only 5 folds and 5 repetitions creating 25 iterations. This will only take 6 minutes.\n\nThroughout this tutorial you will notice that there are many instances where we have to iteratively go through multiple options per problem. Over time, working with different code and algorithms, you will develop an intuition for what is the optimal number of iterative steps for different problems. More is always better - except for the costs of time and computational power. Often you will run into the problem of diminishing returns on very large cross validation steps. If it is crucial you get something as correct as possible you might have to run your computer for a whole week. If you had an unlimited resource of computational power, then the best option would be to run millions of iterations to be sure you have the exact right set of hyperparameters. However, one of the primary roles of the data scientist in a non-infinite world is to determine the optimal solution to trade off questions of accuracy, time, and power. Throughout this tutorial I am trying to give you a sense of that intuition. In this tutorial I am trying to show you the decision points to pay attention to as you gain that experience, so you can be more transparent - to yourself, as well as to others - when documenting your choices in those decision points. However, you will not be perfect at this skill overnight. It will develop over time as you became more familiar with machine learning.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#use all of the cpus on your computer\nparallelStartSocket(cpus = detectCores())\n\n#cross validation procedure for tuning this SVM algorithm\ncvForTuning2 <- makeResampleDesc(\"RepCV\", folds = 5, reps =5)\n\n#Tune the hyperparameters\ntunedSvmPars_RQ1 <- suppressMessages({ \n  tuneParams(\"classif.svm\", task = task_RQ_1, \n             resampling = cvForTuning2, \n             par.set = svm_parametercheck, \n             control = randomsearch)\n})\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntunedSvmPars_RQ1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTune result:\nOp. pars: kernel=polynomial; degree=3; cost=5.74; gamma=9.28\nmmce.test.mean=0.2842099\n```\n\n\n:::\n:::\n\n\n\n\n\n\nNow we have the answer to what some optimal hyperparameter values will be for the SVM for this task! However, if you run the above code multiple times you will notice that you don't get the same results. This is because it isn't searching through every possible option; rather, it tells you the best option from the random hyperparameters it happened to search through this time. This suggests that if this model appears to perform among the best compared to the other models you've evaluated, it's worthwhile to revisit this step and conduct additional cross-validation iterations before settling on the final model hyperparameters.\n\nI ran the above code 3 times, and it always chooses a polynomial for the kernel function so we could set polynomial and then just re-tune the other three hyperparameters. Across the 3 iterations, the algorithm choose degree 2 twice and 3 once. The cost and gamma functions changed more widely with values for cost ranging from 1.99 to 9.28. Values for gamma ranged from 3.93 to 9.28.\n\nLet's put the most recent hyperparameters into the learner and then run the model with our cross validation approach!\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Make the SVM Learner\nSVM_learner_tuned_RQ_1 <- makeLearner(\"classif.svm\", par.vals = tunedSvmPars_RQ1$x)\n\n#Train the model\nSVM_model_RQ_1 <- suppressMessages({ \n  train(learner = SVM_learner_tuned_RQ_1, task = task_RQ_1)\n  })\n\n#Check model performance with LOOCV \nSVM_model_RQ_1_loocv <- suppressMessages({ \n  resample(learner = SVM_learner_tuned_RQ_1, \n           task = task_RQ_1, \n           resampling = loocv, \n           measures = list(mmce, acc))\n  })\n\n#Output the Lost/Cost functions for this model\nSVM_model_RQ_1_loocv$aggr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmmce.test.mean  acc.test.mean \n     0.2824156      0.7175844 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nThe model and cross validation approach took about 6 and a half minutes to run on my 24 CPU computer using all of them in parallel. This model worked about as well as the Decision tree, but better than our KNN. If we took more time to run a wider range of hyperparameters for degree, cost, and gamma, the accuracy of the final model would most likely increase. If you are working through this with me, why don't you create a cross validation procedure with many more iterations, run it, and then go make lunch and come back and rerun the model code. Did you get a higher accuracy rating? (Also how was your lunch?)\n\n### Creating Models for Question 2\n\nThis section will be very similar to the previous learners section, as they have similar constraints and the same predictor variable. The purpose of this section is to show you how to make very small changes in what you feed the model to change the outcome.\n\nLet's jump straight into finding the correct value of k that minimizes misclassifications for the KNN model for research question 2. The only thing that we have to change is the task we feed the `tuneParams` function.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#finding the best value of k\n\n#define values to check. Best to start with checking 1 through 10\nknnParamSpace <- makeParamSet(makeDiscreteParam(\"k\", values = 1:10))\n#tell the computer to search every value of k we offered (1 thru 10)\ngridSearch <- makeTuneControlGrid()\n#cross validate for the k finding\ncvForTuning <- makeResampleDesc(\"RepCV\", folds = 10, reps =20)\n#Use the tuneParams function and the task we made above to get the best k value\ntunedk_RQ_2 <- suppressMessages({ \n  tuneParams(\"classif.knn\",\n             task = task_RQ_2, \n             resampling = cvForTuning, \n             par.set = knnParamSpace, \n             control = gridSearch)\n})\n\ntunedk_RQ_2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTune result:\nOp. pars: k=8\nmmce.test.mean=0.2344251\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe correct k for this research question was 8! Let's update the learner to include this new hyperparameter setting.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknn_learner_RQ_2 <- makeLearner(\"classif.knn\", par.vals = list(\"k\"=8))\n```\n:::\n\n\n\n\n\n\nNow we can run our model with the new learner, task, and cross validation.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Running the KNN model for RQ 2\nKNN_model_RQ_2 <- suppressMessages({ \n  train(learner = knn_learner_RQ_2, task = task_RQ_2)\n})\n\n#Running cross validating\nKNN_model_RQ_2_loocv <- suppressMessages({ \n  resample(learner = knn_learner_RQ_2, \n           task = task_RQ_2, \n           resampling = loocv, \n           measures = list(mmce, acc))\n})\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Looking at how this model did\nKNN_model_RQ_2_loocv$aggr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmmce.test.mean  acc.test.mean \n     0.2344583      0.7655417 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nInterestingly, this model worked better than the previous KNN model with research question 1 (70% vs 77%). So, training score must be slightly more predictive for the nonostensive task.\n\nTo run a decision tree model, we can use the same learner as from research question 1 as we didn't have to do any tuning. Therefore, we can simply run the decision tree model immediately with the pre-made learner, task, and cross validation procedure.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Trainging the Decision Tree model for RQ #2\ndecision_tree_model_RQ_2 <- suppressMessages({ \ntrain(learner = decisiontree_learner_RQ_1_and_2, \n      task = task_RQ_2)\n  })\n                                     \n#Cross validating\ndecision_tree_model_RQ_2_loocv <- suppressMessages({ \n  resample(learner = decisiontree_learner_RQ_1_and_2, \n           task = task_RQ_2, \n           resampling = loocv, \n           measures = list(acc))\n})\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Performance of the Decision Tree\ndecision_tree_model_RQ_2_loocv$aggr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nacc.test.mean \n    0.7655417 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nThis decision tree had the same accuracy as the KNN model for this research question as far as we can tell from the proportion of correct classifications.\n\nNow we have to run the SVM and tune it with the new hyperparameters that work best on this task. Most of what we defined above will work with this algorithm, so we don't need to set new hyperparameters or cv values - we just have to feed the new data to what we already made!\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Tuning hyperparameters for SVM model\ntunedSvmPars_RQ2 <- tuneParams(\"classif.svm\", task = task_RQ_2, resampling = cvForTuning2, par.set = svm_parametercheck, control = randomsearch)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n[Tune] Started tuning learner classif.svm for parameter set:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n           Type len Def                    Constr Req Tunable Trafo\nkernel discrete   -   - polynomial,radial,sigmoid   -    TRUE     -\ndegree  integer   -   -                    1 to 3   -    TRUE     -\ncost    numeric   -   -                 0.1 to 10   -    TRUE     -\ngamma   numeric   -   -                 0.1 to 10   -    TRUE     -\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWith control class: TuneControlRandom\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nImputation value: 1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nExporting objects to slaves for mode socket: .mlr.slave.options\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nMapping in parallel: mode = socket; level = mlr.tuneParams; cpus = 24; elements = 50.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n[Tune] Result: kernel=polynomial; degree=3; cost=8.28; gamma=2.64 : mmce.test.mean=0.2344627\n```\n\n\n:::\n\n```{.r .cell-code}\n#show me what hyperparameters worked best\ntunedSvmPars_RQ2\n\n#update learner with the choosen hyperparameters\nSVM_learner_tuned_RQ_2 <- makeLearner(\"classif.svm\", par.vals = tunedSvmPars_RQ2$x)\n\n#Run the model  \nSVM_model_RQ_2 <- suppressMessages({ \n  train(learner = SVM_learner_tuned_RQ_2, task = task_RQ_2)\n})\n\n#Run Cross Validation\nSVM_model_RQ_2_loocv <- suppressMessages({ \n  resample(learner = SVM_learner_tuned_RQ_2, \n           task = task_RQ_2, \n           resampling = loocv, \n           measures = list(mmce, acc))\n})\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#performance\nSVM_model_RQ_2_loocv$aggr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmmce.test.mean  acc.test.mean \n     0.2344583      0.7655417 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nThis model was also about the same as the decision tree model on accuracy.\n\n### Creating Models for Question 3\n\nThe two models we decided fit with our model assumptions and data for research question 3 are a KNN model and a Random Forest model. We will start by tuning the k hyperparameter for our KNN model. As this has many more predictors than our first two questions, we will investigate with a wider set of ks. If the k that is chosen is at the top of your range (not somewhere in the middle), you haven't searched through a wide enough range of values.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#finding the best value of k\n\n#define values to check best to check 1 through 10\nknnParamSpace <- makeParamSet(makeDiscreteParam(\"k\", values = 1:50))\n#tell the computer to search every value of k we offered (1 thru 10)\ngridSearch <- makeTuneControlGrid()\n#cross validate for the k finding\ncvForTuning <- makeResampleDesc(\"RepCV\", folds = 10, reps =50)\n#Use the tuneParams function and the task we made above to get the best k value\ntunedk_RQ_1 <- tuneParams(\"classif.knn\", task = task_RQ_3_numeric, resampling = cvForTuning, par.set = knnParamSpace, control = gridSearch)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n[Tune] Started tuning learner classif.knn for parameter set:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n      Type len Def                                   Constr Req Tunable Trafo\nk discrete   -   - 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,1...   -    TRUE     -\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWith control class: TuneControlGrid\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nImputation value: 1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nExporting objects to slaves for mode socket: .mlr.slave.options\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nMapping in parallel: mode = socket; level = mlr.tuneParams; cpus = 24; elements = 50.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n[Tune] Result: k=42 : mmce.test.mean=0.2433409\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntunedk_RQ_1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTune result:\nOp. pars: k=42\nmmce.test.mean=0.2433409\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe answer was 35 so we will now use that value of k for our learner.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Creating the KNN learner for RQ1\nknn_learner_RQ_3 <- makeLearner(\"classif.knn\", par.vals = list(\"k\"=35))\n```\n:::\n\n\n\n\n\n\nNow we run the learner with the task and cross validation and get our prediction accuracy.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Training the model \nKNN_model_RQ_3 <- suppressMessages({ \n  train(learner = knn_learner_RQ_3, task = task_RQ_3_numeric)\n})\n\n#cross validating\nKNN_model_RQ_3_loocv <- suppressMessages({ \n  resample(learner = knn_learner_RQ_3, \n           task = task_RQ_3_numeric, \n           resampling = loocv, \n           measures = list(acc))\n})\n\n#Preformance\nKNN_model_RQ_3_loocv$aggr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nacc.test.mean \n    0.7566607 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nThe KNN model for Research Question 3 did about as good as the models trained on fewer predictors (76%).\n\nNext is the random forest algorithm. We can first just make a learner with the `randomForest` model type.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrandomforest_learner_RQ_3 <- makeLearner(\"classif.randomForest\")\n```\n:::\n\n\n\n\n\n\nLike SVM, random forest algothims also have a number of hyperparameters that need to be investigated and tuned to the correct values before we run the model. In random forest the four hyperparameters that should be tuned as best practice before the model can be run are: `ntree` `mtry` `nodesize` and `maxnodes`.\n\n-   `ntree` - the number of trees you want the model to run\n-   `mtry` - the number of features/predictors to sample at each node\n-   `nodesize` - minimum number of observations allowed in a leaf\n-   `maxnodes` - max number of leaves\n\nWe will let the `ntree` and `nodesize` values stay at its default of 500 and 1 respectively as we don't have a particularly large or small amount of data that would suggest we change the default values. These can always be adjusted later after you have tuned anything else. Before we decide what values to choose for the `mtry` and `maxnodes` this is a good time to show you how to check what hyperparameters there are for any specific algorithm. The function `getParamSet` lists the parameters and the default value where applicable.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngetParamSet(\"classif.randomForest\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     Type  len   Def   Constr Req Tunable Trafo\nntree             integer    -   500 1 to Inf   -    TRUE     -\nmtry              integer    -     - 1 to Inf   -    TRUE     -\nreplace           logical    -  TRUE        -   -    TRUE     -\nclasswt     numericvector <NA>     - 0 to Inf   -    TRUE     -\ncutoff      numericvector <NA>     -   0 to 1   -    TRUE     -\nstrata            untyped    -     -        -   -   FALSE     -\nsampsize    integervector <NA>     - 1 to Inf   -    TRUE     -\nnodesize          integer    -     1 1 to Inf   -    TRUE     -\nmaxnodes          integer    -     - 1 to Inf   -    TRUE     -\nimportance        logical    - FALSE        -   -    TRUE     -\nlocalImp          logical    - FALSE        -   -    TRUE     -\nproximity         logical    - FALSE        -   -   FALSE     -\noob.prox          logical    -     -        -   Y   FALSE     -\nnorm.votes        logical    -  TRUE        -   -   FALSE     -\ndo.trace          logical    - FALSE        -   -   FALSE     -\nkeep.forest       logical    -  TRUE        -   -   FALSE     -\nkeep.inbag        logical    - FALSE        -   -   FALSE     -\n```\n\n\n:::\n:::\n\n\n\n\n\n\nNow we know how to look at the tunable parameters, let's go back to deciding how to choose what values to use in tuning with `mtry` and `maxnodes`. We only have 12 predictors, so let's do the full range of 1 to 12 for the number of features to sample at each node. For `maxnodes` we have to choose values less than the number of observations `nrow(training_data)`. For now, let's leave it at null so it can grow without restriction because we aren't as worried about time and computing power with a dataset so small. We only have 1 parameter to tune and so we will do that below:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforestParamSpace <- makeParamSet(makeIntegerParam(\"mtry\", lower = 1, upper = 12))\n\nrandomsearch_100 <- makeTuneControlRandom(maxit = 100)\n\ncvForTuning_randomforest <- makeResampleDesc(\"CV\", iters = 5)\n\ntunedForestPars <- suppressMessages({ \n  tuneParams(learner = randomforest_learner_RQ_3, \n             task = task_RQ_3_factor, \n             resampling = cvForTuning_randomforest,\n             par.set = forestParamSpace, \n             control = randomsearch_100)\n})\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Show the result\ntunedForestPars\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTune result:\nOp. pars: mtry=1\nmmce.test.mean=0.2415613\n```\n\n\n:::\n:::\n\n\n\n\n\n\nAnd the result was that 1 was the best value to use for `mtry`. Now we have to update the learner with the tuned parameter and plug everything into the `resampling` function and make the model.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Update the learner\nrandomforest_learner_RQ_3 <- makeLearner(\"classif.randomForest\", par.vals = list(\"mtry\"=1))\n\n#Train the Model\nrandom_forest_model_RQ_3 <- suppressMessages({ \n  train(learner = randomforest_learner_RQ_3, task = task_RQ_3_factor)\n})\n\n#Cross validating\nrandom_forest_model_RQ_3_loocv <- suppressMessages({ \n  resample(learner = randomforest_learner_RQ_3, \n           task = task_RQ_3_factor, \n           resampling = loocv, \n           measures = list(mmce, acc))\n})\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Performance\nrandom_forest_model_RQ_3_loocv$aggr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmmce.test.mean  acc.test.mean \n     0.2433393      0.7566607 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nBoth the random forest model and the KNN model performed the same when they were cross validated.\n\n## Generic Logistic Regression Example\n\nWhile the current data did not call for us to use logistic regression, it is still a useful algorithm to know how to use for many potential problems. So, here is code that you can use to run your own logistic regression.\n\nWe will use the task we created for research question 1. We will have to make a new learner to define our model using the `classif.logreg` argument for logistic regression. Set the argument `predict.type` equal to `prob` if you want the estimated probabilities of each class outputted, as well as what class each observation is predicted to be in. Then all you have to do is put it together and cross validate:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nLR_learner_RQ_1 <- makeLearner(\"classif.logreg\", predict.type = \"prob\")\n\nLR_model_RQ_1 <- suppressMessages({ \n  train(LR_learner_RQ_1, task_RQ_1)\n})\n\nLR_model_RQ_1_loocv <- suppressMessages({ \n  resample(learner = LR_learner_RQ_1, \n                       task = task_RQ_1,\n                       resampling = loocv)\n})\n\nLR_model_RQ_1_loocv$aggr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmmce.test.mean \n     0.2841918 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nAs predicted, this model did *NOT* do a good job at predicting the correct category for our dogs.\n\n## Generic Naive Bayes Example\n\nAs with logistic regression, we had decided not to use Naive Bayes for this example dataset, but having some base code may be handy for those cases where it would be appropriate. Naive Bayes algorithms only have one hyperparameter to tune, `laplace`. You typically want to add a small value to `laplace`, as it is just a placeholder that adds that value to all of the probabilities to handle the issue of a zero probability for some features. Unseen feature values (0s) are assigned a small, non-zero probability, which helps prevent zero probabilities from making your probabilities be artificially low (as anything multiplied by 0 is 0), and improves the robustness of the Naive Bayes classifier.\n\nI will use the `task_RQ_1` task and we have to make the learner, train the model, and cross validate.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNB_learner_RQ_1 <- makeLearner(\"classif.naiveBayes\", par.vals = list(\"laplace\" = 1))\n  \nNB_model_RQ_1 <- train(learner = NB_learner_RQ_1, \n                       task = task_RQ_1)\n\nNB_model_RQ_1_loocv <- suppressMessages({ \n  resample(learner = NB_learner_RQ_1, \n                       task = task_RQ_1,\n                       resampling = loocv)\n})\n\nNB_model_RQ_1_loocv$aggr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmmce.test.mean \n     0.2841918 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nYou'll notice that we are at about 71.6% accuracy which is less predictive than most of our models. But this and all our other models haven't been tested with new data - let's do that now!\n",
    "supporting": [
      "runningmodels_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}